services:
  db:
    image: postgres:16-alpine
    container_name: entegrasyon-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-baturhan}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: IntegrationDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - entegrasyon-net

  redis:
    image: redis:alpine
    container_name: entegrasyon-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - entegrasyon-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: entegrasyon-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - entegrasyon-net


volumes:
  pgdata:
  redis-data:

networks:
  entegrasyon-net:
    driver: bridge
