version: '3.4'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
  db:
    image: postgres:latest
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: Baturhan
      POSTGRES_PASSWORD: 649471
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  rabbit:
    image: rabbitmq:latest
    container_name: rabbitmq_container
  entegrasyon.api:
    image: ${DOCKER_REGISTRY-}entegrasyonapi
    build:
      context: ./
      dockerfile: Application/Entegrasyon.API/Dockerfile
    depends_on:
      - redis
      - db