version: '3.4'

services:
  redis:
    image: docker.io/redis:latest
    container_name: entegrasyon.redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  db:
    image: postgres:latest
    container_name: entegrasyon.pg_container
    restart: always
    environment:
      POSTGRES_USER: Baturhan
      POSTGRES_PASSWORD: 649471
      POSTGRES_DB: IntegrationDb
    ports:
      - 5432:5432

  pgadmin:
    container_name: entegrasyon.pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

  # entegrasyon.blazor:
  #   image: ${DOCKER_REGISTRY-}entegrasyonblazor
  #   build:
  #     context: ./
  #     dockerfile: Application/Entegrasyon.Blazor/Dockerfile
  #   container_name: entegrasyon.blazor
  #   restart: always
  #   depends_on:
  #     - redis
  #     - db
  #   ports:
  #     - "7070:8080"
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ASPNETCORE_URLS=http://+:8080
  #     - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=IntegrationDb;Username=Baturhan;Password=649471
  #     - ConnectionStrings__Main=Host=db;Port=5432;Database=IntegrationDb;Username=Baturhan;Password=649471
  #     - ConnectionStrings__Redis=redis:6379
