<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Entegrasyon.Desktop</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.Blazor" />
    <PackageReference Include="Velopack" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="MudBlazor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entegrasyon.Entity\Entegrasyon.Entity.csproj" />
    <ProjectReference Include="..\..\Agent\Entegrasyon.PrintAgent.Contracts\Entegrasyon.PrintAgent.Contracts.csproj" />
  </ItemGroup>

</Project>
