// <auto-generated />
using System;
using Entegrasyon.DataAccess.Concrete.EntityFrameworkCore.Contexts;
using Entegrasyon.Entity.Categories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entegrasyon.DataAccess.Concrete.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(IntegrationDbContext))]
    [Migration("20220918162110_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryCategoryAttribute", b =>
                {
                    b.Property<int>("CategoryAttributesId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.HasKey("CategoryAttributesId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryCategoryAttribute");
                });

            modelBuilder.Entity("Entegrasyon.Entity.ApplicationCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identity")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Identity")
                        .IsUnique();

                    b.HasIndex("Name", "Surname")
                        .IsUnique();

                    b.ToTable("ApplicationCustomers");
                });

            modelBuilder.Entity("Entegrasyon.Entity.BranchOffice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BranchOffices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Merkez Ofis"
                        });
                });

            modelBuilder.Entity("Entegrasyon.Entity.Categories.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsConcurrencyToken()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("SuperCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "supCategory"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "subCategory",
                            SuperCategoryId = 1
                        });
                });

            modelBuilder.Entity("Entegrasyon.Entity.Categories.CategoryAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriyAttributeHumanized")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("CategoryAttributeKey")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<bool>("Slicer")
                        .HasColumnType("boolean");

                    b.Property<bool>("Varianter")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("CategoryAttributes");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Categories.CategoryAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryAttributeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryAttributeId");

                    b.ToTable("CategoryAttributeValues");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativeText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsCoverImage")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long?>("ProductVariantId")
                        .HasColumnType("bigint");

                    b.Property<string>("Src")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Logs.ApplicationLog", b =>
                {
                    b.Property<Guid?>("ApplicationUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("LogAction")
                        .HasColumnType("integer");

                    b.Property<int>("LogType")
                        .HasColumnType("integer");

                    b.Property<string>("Object")
                        .HasColumnType("jsonb");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("LogAction");

                    b.HasIndex("LogAction", "LogType");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Entegrasyon.Entity.MarketPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("MarketPlaces");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Matches.CategoryMarketPlaceMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationCategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MarketPlaceCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("MarketPlaceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CategoryMarketPlaceMatches");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Header")
                        .HasMaxLength(60)
                        .HasColumnType("varchar");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ReadDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Orders.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Orders.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("BillingAddressId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Orders.OrderItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Products.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "FirstBrand"
                        });
                });

            modelBuilder.Entity("Entegrasyon.Entity.Products.MainProduct", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text");

                    b.Property<int?>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Header")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("MainProducts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Barcode = "123456798",
                            BrandId = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Header = "Ürün Başlığı",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("Entegrasyon.Entity.Products.ProductVariant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<AttributeKeyValue[]>("AttributeKeyValues")
                        .HasColumnType("jsonb");

                    b.Property<int>("BranchOfficeId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyType")
                        .HasColumnType("text");

                    b.Property<int>("CurrentStockQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasComputedColumnSql("(\"Quantity\")-(\"SoldQuantity\")", true);

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("DimensionalWeight")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("money");

                    b.Property<long>("ProductMainId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("money");

                    b.Property<int>("SoldQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("StockCode")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BranchOfficeId");

                    b.HasIndex("ProductMainId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BranchOfficeId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrencyType = "₺",
                            CurrentStockQuantity = 50,
                            Description = "Açıklama",
                            IsDeleted = false,
                            ListPrice = 50m,
                            ProductMainId = 1L,
                            Quantity = 0,
                            SalePrice = 54m,
                            SoldQuantity = 0,
                            StockCode = "22qwe123456",
                            Title = "Başlık",
                            VatRate = 8m
                        },
                        new
                        {
                            Id = 2L,
                            BranchOfficeId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrencyType = "₺",
                            CurrentStockQuantity = 30,
                            Description = "Açıklama 2",
                            IsDeleted = false,
                            ListPrice = 50m,
                            ProductMainId = 1L,
                            Quantity = 0,
                            SalePrice = 54m,
                            SoldQuantity = 0,
                            StockCode = "22qwe123456",
                            Title = "Başlık 2",
                            VatRate = 8m
                        });
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.ChangeProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ChangeProducts");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.DiscountVoucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("DiscountVouchers");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.ReturnProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ReturnProducts");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SalePersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalePersonId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.SaleItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ProductVariantId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems");
                });

            modelBuilder.Entity("RootClaimRootRole", b =>
                {
                    b.Property<int>("ClaimsId")
                        .HasColumnType("integer");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("ClaimsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("RootClaimRootRole");

                    b.HasData(
                        new
                        {
                            ClaimsId = 1,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 2,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 3,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 4,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 5,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 6,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 7,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 8,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 9,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 10,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 11,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 12,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 13,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 14,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 15,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 16,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 17,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 18,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 19,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 20,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 21,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 22,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 23,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 24,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 25,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 26,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 27,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 30,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 31,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 32,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 33,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 34,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 35,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 36,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 37,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 38,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 39,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 40,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 41,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 42,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 43,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 44,
                            RolesId = 1
                        },
                        new
                        {
                            ClaimsId = 45,
                            RolesId = 1
                        });
                });

            modelBuilder.Entity("Shared.User.RootClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.HasKey("Id");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ürün ekleme yetkisi.",
                            IsDeleted = false,
                            Name = "product.Add"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ürün silme yetkisi.",
                            IsDeleted = false,
                            Name = "product.Delete"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ürün güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "product.Update"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ürün listeleme yetkisi.",
                            IsDeleted = false,
                            Name = "product.List"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Satış yapma yetkisi.",
                            IsDeleted = false,
                            Name = "sale.Add"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Satış düzenleme yetkisi.",
                            IsDeleted = false,
                            Name = "sale.Update"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Şube ekleme yetkisi.",
                            IsDeleted = false,
                            Name = "branchOffice.Add"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Şube düzenleme yetkisi.",
                            IsDeleted = false,
                            Name = "branchOffice.Update"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Şube silme yetkisi.",
                            IsDeleted = false,
                            Name = "branchOffice.Delete"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kategori silme yetkisi.",
                            IsDeleted = false,
                            Name = "category.Add"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kategori güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "category.Update"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kategori görebilme yetkisi.",
                            IsDeleted = false,
                            Name = "category.List"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kategori silme yetkisi.",
                            IsDeleted = false,
                            Name = "category.Delete"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ofis görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "branchOffice.List"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Satış görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "sale.List"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Satış silme yetkisi.",
                            IsDeleted = false,
                            Name = "sale.Delete"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müşteri ekleme yetkisi.",
                            IsDeleted = false,
                            Name = "customer.Add"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müşteri güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "customer.Update"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müşteri görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "customer.List"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Müşteri silme yetkisi.",
                            IsDeleted = false,
                            Name = "customer.Delete"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Satış ekleme yetkisi.",
                            IsDeleted = false,
                            Name = "order.Add"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Satış güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "order.Update"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Satış görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "order.List"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Satış silme yetkisi.",
                            IsDeleted = false,
                            Name = "order.Delete"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rapor ekleme yetkisi.",
                            IsDeleted = false,
                            Name = "report.Add"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rapor güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "report.Update"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rapor görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "report.List"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Rapor silme yetkisi.",
                            IsDeleted = false,
                            Name = "report.Delete"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kargo ekleme yetkisi.",
                            IsDeleted = false,
                            Name = "cargo.Add"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kargo güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "cargo.Update"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kargo görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "cargo.List"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kargo silme yetkisi.",
                            IsDeleted = false,
                            Name = "cargo.Delete"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Entegrasyon ekleme yetkisi.",
                            IsDeleted = false,
                            Name = "integration.Add"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Entegrasyon güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "integration.Update"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Entegrasyon görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "integration.List"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Entegrasyon silme yetkisi.",
                            IsDeleted = false,
                            Name = "integration.Delete"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kullanıcı ekleme yetkisi.",
                            IsDeleted = false,
                            Name = "user.Add"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kullanıcı güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "user.Update"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kullanıcı görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "user.List"
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Kullanıcı silme yetkisi.",
                            IsDeleted = false,
                            Name = "user.Delete"
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Sistem kaydı görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "log.List"
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ayar güncelleme yetkisi.",
                            IsDeleted = false,
                            Name = "setting.Update"
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Ayar görüntüleme yetkisi.",
                            IsDeleted = false,
                            Name = "setting.List"
                        });
                });

            modelBuilder.Entity("Shared.User.RootLogin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RootUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RootUserId");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Shared.User.RootRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Shared.User.RootUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTwoFactorAuthActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MobileJwtToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("MobileJwtTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("NeedsTakeNewPassword")
                        .HasColumnType("boolean");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)");

                    b.Property<string>("TemporaryPassword")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("WebJwtToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("WebJwtTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RootUser");
                });

            modelBuilder.Entity("Entegrasyon.Entity.ApplicationUser", b =>
                {
                    b.HasBaseType("Shared.User.RootUser");

                    b.Property<int?>("DefaultBranchOfficeId")
                        .HasColumnType("integer");

                    b.HasIndex("DefaultBranchOfficeId");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dfda5d4a-f807-408c-9b4d-908830ad5724"),
                            CreatedAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@admin.com",
                            IsActive = true,
                            IsDeleted = false,
                            IsTwoFactorAuthActive = false,
                            MobileJwtTokenExpiresAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Admin",
                            NeedsTakeNewPassword = true,
                            NormalizedUserName = "ADMIN",
                            RoleId = 1,
                            Surname = "Admin",
                            TemporaryPassword = "Admin",
                            UserName = "Admin",
                            WebJwtTokenExpiresAt = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DefaultBranchOfficeId = 1
                        });
                });

            modelBuilder.Entity("CategoryCategoryAttribute", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Categories.CategoryAttribute", null)
                        .WithMany()
                        .HasForeignKey("CategoryAttributesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entegrasyon.Entity.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entegrasyon.Entity.Categories.Category", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Categories.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Categories.CategoryAttributeValue", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Categories.CategoryAttribute", null)
                        .WithMany("CategoryAttributeValues")
                        .HasForeignKey("CategoryAttributeId");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Image", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Products.ProductVariant", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductVariantId");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Logs.ApplicationLog", b =>
                {
                    b.HasOne("Entegrasyon.Entity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Orders.Order", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Orders.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId");

                    b.HasOne("Entegrasyon.Entity.Orders.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");

                    b.Navigation("BillingAddress");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Orders.OrderItem", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entegrasyon.Entity.Products.ProductVariant", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Products.MainProduct", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Products.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("Entegrasyon.Entity.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Products.ProductVariant", b =>
                {
                    b.HasOne("Entegrasyon.Entity.BranchOffice", "BranchOffice")
                        .WithMany()
                        .HasForeignKey("BranchOfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entegrasyon.Entity.Products.MainProduct", "ProductMain")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductMainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchOffice");

                    b.Navigation("ProductMain");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.ReturnProduct", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Products.ProductVariant", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.Sale", b =>
                {
                    b.HasOne("Entegrasyon.Entity.ApplicationCustomer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId");

                    b.HasOne("Entegrasyon.Entity.ApplicationUser", "SalePerson")
                        .WithMany()
                        .HasForeignKey("SalePersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SalePerson");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.SaleItem", b =>
                {
                    b.HasOne("Entegrasyon.Entity.Products.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId");

                    b.HasOne("Entegrasyon.Entity.Sales.Sale", null)
                        .WithMany("SaleItems")
                        .HasForeignKey("SaleId");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("RootClaimRootRole", b =>
                {
                    b.HasOne("Shared.User.RootClaim", null)
                        .WithMany()
                        .HasForeignKey("ClaimsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.User.RootRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.User.RootLogin", b =>
                {
                    b.HasOne("Shared.User.RootUser", "RootUser")
                        .WithMany("Logins")
                        .HasForeignKey("RootUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RootUser");
                });

            modelBuilder.Entity("Shared.User.RootUser", b =>
                {
                    b.HasOne("Shared.User.RootRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entegrasyon.Entity.ApplicationUser", b =>
                {
                    b.HasOne("Entegrasyon.Entity.BranchOffice", "DefaultBranchOffice")
                        .WithMany("Users")
                        .HasForeignKey("DefaultBranchOfficeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultBranchOffice");
                });

            modelBuilder.Entity("Entegrasyon.Entity.ApplicationCustomer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Entegrasyon.Entity.BranchOffice", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Categories.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Categories.CategoryAttribute", b =>
                {
                    b.Navigation("CategoryAttributeValues");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Products.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Products.MainProduct", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Products.ProductVariant", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Entegrasyon.Entity.Sales.Sale", b =>
                {
                    b.Navigation("SaleItems");
                });

            modelBuilder.Entity("Shared.User.RootRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Shared.User.RootUser", b =>
                {
                    b.Navigation("Logins");
                });
#pragma warning restore 612, 618
        }
    }
}
