<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>d595da3d-8338-48f7-93a6-7d9f61614d22</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<PropertyGroup>
		<WarningLevel>6</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
		<Watch Remove="Logs\**" />
	</ItemGroup>

	<ItemGroup>
		<None Update="wwwroot\styles\**\*">
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
<PackageReference Include="Microsoft.CodeAnalysis.Common" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" />
		<PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
		<PackageReference Include="MudBlazor" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
		<PackageReference Include="Serilog.Sinks.Grafana.Loki" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Entegrasyon.Business\Entegrasyon.Business.csproj" />
		<ProjectReference Include="..\Entegrasyon.ApplicationBootstrap\Entegrasyon.ApplicationBootstrap.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Utility\ToastrNotification\" />
		<Folder Include="ViewModels\Office\" />
		<Folder Include="ViewModels\User\" />
		<Folder Include="wwwroot\img\auth\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="compilerconfig.json" />
	</ItemGroup>


</Project>
