<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>d595da3d-8338-48f7-93a6-7d9f61614d22</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<PropertyGroup>
		<WarningLevel>6</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
		<Watch Remove="Logs\**" />
	</ItemGroup>

	<ItemGroup>
		<None Update="wwwroot\styles\**\*">
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.13.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.13.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common" Version="4.13.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" Version="4.13.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.15" />
		<PackageReference Include="MudBlazor" Version="8.15.0" />
		<PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.*" />
		<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.*" />
		<PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.*" />
		<PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.15.0-beta.1" />
		<PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.*" />
		<PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="8.3.2" />
		<PackageReference Include="System.Text.Json" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Entegrasyon.Business\Entegrasyon.Business.csproj" />
		<ProjectReference Include="..\Entegrasyon.ApplicationBootstrap\Entegrasyon.ApplicationBootstrap.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Utility\ToastrNotification\" />
		<Folder Include="ViewModels\Office\" />
		<Folder Include="ViewModels\User\" />
		<Folder Include="wwwroot\img\auth\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="compilerconfig.json" />
	</ItemGroup>


</Project>
