<Project Sdk="Microsoft.NET.Sdk.Web">

	<Target Name="PreBuild" BeforeTargets="PreBuildEvent">
		<Exec Command="npm install" />
	</Target>
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>d595da3d-8338-48f7-93a6-7d9f61614d22</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<DockerfileContext>..\..</DockerfileContext>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningLevel>6</WarningLevel>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningLevel>6</WarningLevel>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="compilerconfig.json" />
	</ItemGroup>
	<ItemGroup>
		<None Update="wwwroot\styles\**\*">
			<CopyToPublishDirectory>Never</CopyToPublishDirectory>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Mapster" Version="7.4.0" />
		<PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.15" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.13.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.Scripting.Common" Version="4.13.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.15">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.15" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
		<PackageReference Include="System.Text.Json" Version="8.0.5" />
		<PackageReference Include="WolverineFx" Version="3.12.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Entegrasyon.Business\Entegrasyon.Business.csproj" />
		<ProjectReference Include="..\Entegrasyon.DependencyResolver\Entegrasyon.DependencyResolver.csproj" />
		<ProjectReference Include="..\Entegrasyon.MessageQueue\Entegrasyon.MessageQueue.Handler.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Utility\ToastrNotification\" />
		<Folder Include="ViewModels\Office\" />
		<Folder Include="ViewModels\User\" />
		<Folder Include="wwwroot\img\auth\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="compilerconfig.json" />
	</ItemGroup>

</Project>
