<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Concrete\EntityFrameworkCore\Contexts\Seed\" />
    <Folder Include="Concrete\EntityFrameworkCore\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entegrasyon.Entity\Entegrasyon.Entity.csproj" />
  </ItemGroup>

</Project>
