// <auto-generated />
using System;
using Entegrasyon.AdminPanel.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Entegrasyon.AdminPanel.Migrations
{
    [DbContext(typeof(AdminPanelDbContext))]
    [Migration("20260330232254_AddMasterCargoCompany")]
    partial class AddMasterCargoCompany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.AiCreditAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImageGenerationCredits")
                        .HasColumnType("integer");

                    b.Property<int>("ProductDescriptionCredits")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("AiCreditAccounts");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.AiCreditTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AiCreditAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreditType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AiCreditAccountId");

                    b.ToTable("AiCreditTransactions");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.ApplicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.FeaturePackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FeaturePackages");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.FeaturePackagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeaturePackageId")
                        .HasColumnType("integer");

                    b.Property<string>("PermissionKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FeaturePackageId");

                    b.ToTable("FeaturePackagePermissions");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MarketplaceReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MarketplaceId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentExternalId")
                        .HasColumnType("text");

                    b.Property<string>("RawJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarketplaceId", "EntityType", "ExternalId")
                        .IsUnique();

                    b.ToTable("MarketplaceReferences");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowCustom")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HumanizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MasterAttributes");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttributeMarketplaceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalAttributeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalAttributeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MarketplaceId")
                        .HasColumnType("integer");

                    b.Property<int>("MasterAttributeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterAttributeId", "MarketplaceId")
                        .IsUnique();

                    b.ToTable("MasterAttributeMarketplaceMappings");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttributeValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MasterAttributeId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MasterAttributeId");

                    b.ToTable("MasterAttributeValues");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MasterBrands");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterBrandMarketplaceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExternalBrandId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalBrandName")
                        .HasColumnType("text");

                    b.Property<int>("MarketplaceId")
                        .HasColumnType("integer");

                    b.Property<int>("MasterBrandId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterBrandId", "MarketplaceId")
                        .IsUnique();

                    b.ToTable("MasterBrandMarketplaceMappings");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCargoCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MasterCargoCompanies");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCargoCompanyMarketplaceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExternalCargoCompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalCargoCompanyName")
                        .HasColumnType("text");

                    b.Property<int>("MarketplaceId")
                        .HasColumnType("integer");

                    b.Property<int>("MasterCargoCompanyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterCargoCompanyId", "MarketplaceId")
                        .IsUnique();

                    b.ToTable("MasterCargoCompanyMarketplaceMappings");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalExternalId")
                        .HasColumnType("text");

                    b.Property<int?>("OriginalMarketplaceId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MasterCategories");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategoryAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSlicer")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVarianter")
                        .HasColumnType("boolean");

                    b.Property<int>("MasterAttributeId")
                        .HasColumnType("integer");

                    b.Property<int>("MasterCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterAttributeId");

                    b.HasIndex("MasterCategoryId", "MasterAttributeId")
                        .IsUnique();

                    b.ToTable("MasterCategoryAttributes");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategoryMarketplaceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalCategoryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalCategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MarketplaceId")
                        .HasColumnType("integer");

                    b.Property<int>("MasterCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterCategoryId", "MarketplaceId")
                        .IsUnique();

                    b.ToTable("MasterCategoryMarketplaceMappings");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterValueMarketplaceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ExternalValueId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalValueName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MarketplaceId")
                        .HasColumnType("integer");

                    b.Property<int>("MasterAttributeValueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterAttributeValueId", "MarketplaceId")
                        .IsUnique();

                    b.ToTable("MasterValueMarketplaceMappings");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.SectorPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IconName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SectorPackages");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.SectorPackageCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("SectorPackageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MasterCategoryId");

                    b.HasIndex("SectorPackageId");

                    b.ToTable("SectorPackageCategories");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DatabaseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Subdomain")
                        .IsUnique();

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.TenantLicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantLicenses");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.TenantSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FeaturePackageId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FeaturePackageId");

                    b.HasIndex("TenantId");

                    b.ToTable("TenantSubscriptions");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.AiCreditAccount", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.Tenant", "Tenant")
                        .WithOne("AiCreditAccount")
                        .HasForeignKey("Entegrasyon.AdminPanel.Infrastructure.Data.AiCreditAccount", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.AiCreditTransaction", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.AiCreditAccount", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AiCreditAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.ApplicationLog", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.Tenant", "Tenant")
                        .WithMany("ApplicationLogs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.FeaturePackagePermission", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.FeaturePackage", "Package")
                        .WithMany("Permissions")
                        .HasForeignKey("FeaturePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttributeMarketplaceMapping", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttribute", "MasterAttribute")
                        .WithMany("MarketplaceMappings")
                        .HasForeignKey("MasterAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterAttribute");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttributeValue", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttribute", "MasterAttribute")
                        .WithMany("Values")
                        .HasForeignKey("MasterAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterAttribute");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterBrandMarketplaceMapping", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterBrand", "MasterBrand")
                        .WithMany("MarketplaceMappings")
                        .HasForeignKey("MasterBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterBrand");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCargoCompanyMarketplaceMapping", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCargoCompany", "MasterCargoCompany")
                        .WithMany("MarketplaceMappings")
                        .HasForeignKey("MasterCargoCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterCargoCompany");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategory", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategoryAttribute", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttribute", "MasterAttribute")
                        .WithMany("CategoryLinks")
                        .HasForeignKey("MasterAttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategory", "MasterCategory")
                        .WithMany("CategoryAttributes")
                        .HasForeignKey("MasterCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterAttribute");

                    b.Navigation("MasterCategory");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategoryMarketplaceMapping", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategory", "MasterCategory")
                        .WithMany("MarketplaceMappings")
                        .HasForeignKey("MasterCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterCategory");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterValueMarketplaceMapping", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttributeValue", "MasterAttributeValue")
                        .WithMany("MarketplaceMappings")
                        .HasForeignKey("MasterAttributeValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterAttributeValue");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.SectorPackageCategory", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategory", "MasterCategory")
                        .WithMany("SectorPackageCategories")
                        .HasForeignKey("MasterCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.SectorPackage", "SectorPackage")
                        .WithMany("Categories")
                        .HasForeignKey("SectorPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterCategory");

                    b.Navigation("SectorPackage");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.TenantLicense", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.Tenant", "Tenant")
                        .WithMany("Licenses")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.TenantSubscription", b =>
                {
                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.FeaturePackage", "Package")
                        .WithMany("Subscriptions")
                        .HasForeignKey("FeaturePackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entegrasyon.AdminPanel.Infrastructure.Data.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.AiCreditAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.FeaturePackage", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttribute", b =>
                {
                    b.Navigation("CategoryLinks");

                    b.Navigation("MarketplaceMappings");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterAttributeValue", b =>
                {
                    b.Navigation("MarketplaceMappings");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterBrand", b =>
                {
                    b.Navigation("MarketplaceMappings");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCargoCompany", b =>
                {
                    b.Navigation("MarketplaceMappings");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.MasterCategory", b =>
                {
                    b.Navigation("CategoryAttributes");

                    b.Navigation("Children");

                    b.Navigation("MarketplaceMappings");

                    b.Navigation("SectorPackageCategories");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.MasterCatalog.SectorPackage", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Entegrasyon.AdminPanel.Infrastructure.Data.Tenant", b =>
                {
                    b.Navigation("AiCreditAccount");

                    b.Navigation("ApplicationLogs");

                    b.Navigation("Licenses");
                });
#pragma warning restore 612, 618
        }
    }
}
