<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entegrasyon.DataAccess\Entegrasyon.DataAccess.csproj" />
    <ProjectReference Include="..\Entegrasyon.MessageQueue.Commands\Entegrasyon.MessageQueue.Commands.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Notifications\Emails\" />
    <Folder Include="Utility\Auth\" />
  </ItemGroup>

</Project>
