<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared\Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Brands\Import\" />
    <Folder Include="Dtos\CargoCompany\" />
    <Folder Include="Barcode\" />
    <Folder Include="Dtos\Attributes\" />
    <Folder Include="Tenants\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
