<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Minio" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Entegrasyon.Business\Entegrasyon.Business.csproj" />
    <ProjectReference Include="..\Entegrasyon.AdminPanel\Entegrasyon.AdminPanel.csproj" />
  </ItemGroup>

</Project>
